/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.joanhermay.sistema_sic;

import com.github.joanhermay.sistema_sic.catalogo.vistas.VistaRegistroEdicionCatalogoDeCuentas;
import com.github.joanhermay.sistema_sic.librodiario.vistas.VistaRegistroEdicionAsientosDeDiario;
import com.github.joanhermay.sistema_sic.librodiario.vistas.VistaRegistroEdicionMovimientos;
import java.awt.event.ActionListener;

/**
 *
 * @author joanhermay
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private VistaRegistroEdicionAsientosDeDiario registroEdicionAsientosDeDiario;
    private VistaRegistroEdicionMovimientos registroEdicionMovimientos;
    
    

    /**
     * Creates new form Principal
     */
    public VistaPrincipal() {
        initComponents();
        initCustomAppComponents();
    }
    
    
    private void initCustomAppComponents() {
        registroEdicionAsientosDeDiario = new VistaRegistroEdicionAsientosDeDiario(this, true);
        registroEdicionAsientosDeDiario.setLocationRelativeTo(this);
        
        registroEdicionMovimientos = new VistaRegistroEdicionMovimientos(this, true);
        registroEdicionMovimientos.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        txtTituloApp = new javax.swing.JLabel();
        panelGlobal = new javax.swing.JPanel();
        panelPeriodoContable = new javax.swing.JPanel();
        txtAnioPeriodoContable = new javax.swing.JLabel();
        txtMesPeriodoContable = new javax.swing.JLabel();
        cbAnioPeriodoContable = new javax.swing.JComboBox<>();
        cbMesPeriodoContable = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panelTabGlobal = new javax.swing.JTabbedPane();
        panelTabLibroDiario = new javax.swing.JPanel();
        panelAsientos = new javax.swing.JPanel();
        panelTablaAsientos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAsientosDeDiario = new javax.swing.JTable();
        btnRegistrarEditarNuevoAsientoDeDiario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelMovimientos = new javax.swing.JPanel();
        panelTablaMovimientos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMovimientosDeAsientosDeDiario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        btnEditarMovimiento = new javax.swing.JButton();
        panelTabLibroMayor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMovimientosCuentaEspecificaLibroMayor = new javax.swing.JTable();
        panelTotales = new javax.swing.JPanel();
        txtTotalDebeLibroMayor = new javax.swing.JLabel();
        ftxtTotalDebeLibroMayor = new javax.swing.JFormattedTextField();
        txtTotalHaberLibroMayor = new javax.swing.JLabel();
        ftxtTotalHaberLibroMayor = new javax.swing.JFormattedTextField();
        txtSaltoTotalCuentaLibroMayor = new javax.swing.JLabel();
        ftxtSaldoTotalCuentaLibroMayor = new javax.swing.JFormattedTextField();
        txtCuentaLibroMayor = new javax.swing.JLabel();
        cbCuentaAMostrarLibroMayor = new javax.swing.JComboBox<>();
        panelTabBalanceGeneral = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        panelTabEstadoDeResultado = new javax.swing.JPanel();
        barraMenuOpciones = new javax.swing.JMenuBar();
        menuAcciones = new javax.swing.JMenu();
        menuItemCrearPeriodoContable = new javax.swing.JMenuItem();
        munuItemVerCatalogoDeCuenta = new javax.swing.JMenuItem();
        munuItemCostoDeManoDeObra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        panelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTituloApp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTituloApp.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloApp, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPeriodoContable.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodo Contable"));

        txtAnioPeriodoContable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnioPeriodoContable.setText("Año");

        txtMesPeriodoContable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMesPeriodoContable.setText("Mes");

        cbAnioPeriodoContable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020" }));
        cbAnioPeriodoContable.setAlignmentX(0.0F);

        cbMesPeriodoContable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Octubre", "Septiembre", "Agosto" }));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ESTADO");

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("EN CURSO / CERRADO");
        jTextField2.setFocusable(false);

        jButton1.setText("Cerrar Periodo");

        javax.swing.GroupLayout panelPeriodoContableLayout = new javax.swing.GroupLayout(panelPeriodoContable);
        panelPeriodoContable.setLayout(panelPeriodoContableLayout);
        panelPeriodoContableLayout.setHorizontalGroup(
            panelPeriodoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodoContableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeriodoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeriodoContableLayout.createSequentialGroup()
                        .addComponent(txtAnioPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAnioPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPeriodoContableLayout.createSequentialGroup()
                        .addComponent(txtMesPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMesPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(panelPeriodoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeriodoContableLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPeriodoContableLayout.setVerticalGroup(
            panelPeriodoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodoContableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPeriodoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnioPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAnioPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPeriodoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeriodoContableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMesPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbMesPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeriodoContableLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        panelTabLibroDiario.setLayout(new java.awt.GridLayout(1, 2));

        panelTablaAsientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Asientos Diario"));

        tbAsientosDeDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Asiento", "Fecha", "Concepto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAsientosDeDiario.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbAsientosDeDiario);
        if (tbAsientosDeDiario.getColumnModel().getColumnCount() > 0) {
            tbAsientosDeDiario.getColumnModel().getColumn(0).setResizable(false);
            tbAsientosDeDiario.getColumnModel().getColumn(1).setResizable(false);
            tbAsientosDeDiario.getColumnModel().getColumn(2).setResizable(false);
        }

        btnRegistrarEditarNuevoAsientoDeDiario.setText("Registrar nuevo asiento");

        jButton2.setText("Eliminar asiento");
        jButton2.setEnabled(false);

        jButton3.setText("Editar asiento");
        jButton3.setEnabled(false);

        javax.swing.GroupLayout panelTablaAsientosLayout = new javax.swing.GroupLayout(panelTablaAsientos);
        panelTablaAsientos.setLayout(panelTablaAsientosLayout);
        panelTablaAsientosLayout.setHorizontalGroup(
            panelTablaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaAsientosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaAsientosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarEditarNuevoAsientoDeDiario)))
                .addContainerGap())
        );
        panelTablaAsientosLayout.setVerticalGroup(
            panelTablaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaAsientosLayout.createSequentialGroup()
                .addGroup(panelTablaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarEditarNuevoAsientoDeDiario)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsientosLayout.createSequentialGroup()
                .addComponent(panelTablaAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsientosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTablaAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTabLibroDiario.add(panelAsientos);

        panelTablaMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos de asiento"));

        tbMovimientosDeAsientosDeDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Cuenta", "Nombre Cuenta", "Parcial", "Debe", "Haber"
            }
        ));
        jScrollPane3.setViewportView(tbMovimientosDeAsientosDeDiario);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Debe");

        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField4.setEnabled(false);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Haber");

        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setEnabled(false);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Saldo");

        jFormattedTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField9.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextField4)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jFormattedTextField8)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextField9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEditarMovimiento.setText("Editar movimiento");
        btnEditarMovimiento.setEnabled(false);

        javax.swing.GroupLayout panelTablaMovimientosLayout = new javax.swing.GroupLayout(panelTablaMovimientos);
        panelTablaMovimientos.setLayout(panelTablaMovimientosLayout);
        panelTablaMovimientosLayout.setHorizontalGroup(
            panelTablaMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaMovimientosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaMovimientosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarMovimiento)))
                .addContainerGap())
        );
        panelTablaMovimientosLayout.setVerticalGroup(
            panelTablaMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaMovimientosLayout.createSequentialGroup()
                .addComponent(btnEditarMovimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMovimientosLayout = new javax.swing.GroupLayout(panelMovimientos);
        panelMovimientos.setLayout(panelMovimientosLayout);
        panelMovimientosLayout.setHorizontalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovimientosLayout.createSequentialGroup()
                .addComponent(panelTablaMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMovimientosLayout.setVerticalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMovimientosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTablaMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTabLibroDiario.add(panelMovimientos);

        panelTabGlobal.addTab("Libro Diario", panelTabLibroDiario);

        tbMovimientosCuentaEspecificaLibroMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cuenta", "Fecha", "Debe", "Haber"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMovimientosCuentaEspecificaLibroMayor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbMovimientosCuentaEspecificaLibroMayor);

        panelTotales.setBorder(javax.swing.BorderFactory.createTitledBorder("Totales"));
        panelTotales.setLayout(new java.awt.GridLayout(3, 2, 0, 5));

        txtTotalDebeLibroMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalDebeLibroMayor.setText("DEBE");
        panelTotales.add(txtTotalDebeLibroMayor);

        ftxtTotalDebeLibroMayor.setEditable(false);
        ftxtTotalDebeLibroMayor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("$ ###,###,###,##0.##"))));
        ftxtTotalDebeLibroMayor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxtTotalDebeLibroMayor.setEnabled(false);
        panelTotales.add(ftxtTotalDebeLibroMayor);

        txtTotalHaberLibroMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalHaberLibroMayor.setText("HABER");
        panelTotales.add(txtTotalHaberLibroMayor);

        ftxtTotalHaberLibroMayor.setEditable(false);
        ftxtTotalHaberLibroMayor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("$ ###,###,###,##0.##"))));
        ftxtTotalHaberLibroMayor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxtTotalHaberLibroMayor.setEnabled(false);
        panelTotales.add(ftxtTotalHaberLibroMayor);

        txtSaltoTotalCuentaLibroMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSaltoTotalCuentaLibroMayor.setText("SALDO TOTAL");
        panelTotales.add(txtSaltoTotalCuentaLibroMayor);

        ftxtSaldoTotalCuentaLibroMayor.setEditable(false);
        ftxtSaldoTotalCuentaLibroMayor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("$ ###,###,###,##0.##"))));
        ftxtSaldoTotalCuentaLibroMayor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftxtSaldoTotalCuentaLibroMayor.setEnabled(false);
        panelTotales.add(ftxtSaldoTotalCuentaLibroMayor);

        txtCuentaLibroMayor.setText("Cuenta");

        cbCuentaAMostrarLibroMayor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelTabLibroMayorLayout = new javax.swing.GroupLayout(panelTabLibroMayor);
        panelTabLibroMayor.setLayout(panelTabLibroMayorLayout);
        panelTabLibroMayorLayout.setHorizontalGroup(
            panelTabLibroMayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabLibroMayorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabLibroMayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, panelTabLibroMayorLayout.createSequentialGroup()
                        .addComponent(txtCuentaLibroMayor)
                        .addGap(40, 40, 40)
                        .addComponent(cbCuentaAMostrarLibroMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTabLibroMayorLayout.setVerticalGroup(
            panelTabLibroMayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabLibroMayorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabLibroMayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtCuentaLibroMayor)
                    .addComponent(cbCuentaAMostrarLibroMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTabGlobal.addTab("Libro Mayor", panelTabLibroMayor);

        panelTabBalanceGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cuenta", "Debe", "Haber", "Acreedor", "Deudor"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TOTAL DEBE");
        jPanel6.add(jLabel5);

        jFormattedTextField5.setEditable(false);
        jFormattedTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(jFormattedTextField5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TOTAL HABER");
        jPanel6.add(jLabel6);

        jFormattedTextField6.setEditable(false);
        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(jFormattedTextField6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DIFERENCIA");
        jPanel6.add(jLabel7);

        jFormattedTextField7.setEditable(false);
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(jFormattedTextField7);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOTAL ACREEDOR");
        jPanel7.add(jLabel1);

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jFormattedTextField1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL DEUDOR");
        jPanel7.add(jLabel2);

        jFormattedTextField2.setEditable(false);
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jFormattedTextField2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DIFERENCIA");
        jPanel7.add(jLabel3);

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jFormattedTextField3);

        jPanel5.add(jPanel7);

        javax.swing.GroupLayout panelTabBalanceGeneralLayout = new javax.swing.GroupLayout(panelTabBalanceGeneral);
        panelTabBalanceGeneral.setLayout(panelTabBalanceGeneralLayout);
        panelTabBalanceGeneralLayout.setHorizontalGroup(
            panelTabBalanceGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabBalanceGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabBalanceGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTabBalanceGeneralLayout.setVerticalGroup(
            panelTabBalanceGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabBalanceGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTabGlobal.addTab("Balance General", panelTabBalanceGeneral);

        panelTabEstadoDeResultado.setEnabled(false);

        javax.swing.GroupLayout panelTabEstadoDeResultadoLayout = new javax.swing.GroupLayout(panelTabEstadoDeResultado);
        panelTabEstadoDeResultado.setLayout(panelTabEstadoDeResultadoLayout);
        panelTabEstadoDeResultadoLayout.setHorizontalGroup(
            panelTabEstadoDeResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1178, Short.MAX_VALUE)
        );
        panelTabEstadoDeResultadoLayout.setVerticalGroup(
            panelTabEstadoDeResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        panelTabGlobal.addTab("Estado de resultado", panelTabEstadoDeResultado);

        javax.swing.GroupLayout panelGlobalLayout = new javax.swing.GroupLayout(panelGlobal);
        panelGlobal.setLayout(panelGlobalLayout);
        panelGlobalLayout.setHorizontalGroup(
            panelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTabGlobal)
                    .addGroup(panelGlobalLayout.createSequentialGroup()
                        .addComponent(panelPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelGlobalLayout.setVerticalGroup(
            panelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPeriodoContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabGlobal)
                .addContainerGap())
        );

        menuAcciones.setText("Acciones");

        menuItemCrearPeriodoContable.setText("Crear nuevo periodo contable");
        menuAcciones.add(menuItemCrearPeriodoContable);

        munuItemVerCatalogoDeCuenta.setText("Ver Catalogo de cuentas");
        menuAcciones.add(munuItemVerCatalogoDeCuenta);

        munuItemCostoDeManoDeObra.setText("Costo de mano de obra");
        menuAcciones.add(munuItemCostoDeManoDeObra);

        barraMenuOpciones.add(menuAcciones);

        setJMenuBar(barraMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar barraMenuOpciones;
    public javax.swing.JButton btnEditarMovimiento;
    public javax.swing.JButton btnRegistrarEditarNuevoAsientoDeDiario;
    public javax.swing.JComboBox<String> cbAnioPeriodoContable;
    public javax.swing.JComboBox<String> cbCuentaAMostrarLibroMayor;
    public javax.swing.JComboBox<String> cbMesPeriodoContable;
    public javax.swing.JFormattedTextField ftxtSaldoTotalCuentaLibroMayor;
    public javax.swing.JFormattedTextField ftxtTotalDebeLibroMayor;
    public javax.swing.JFormattedTextField ftxtTotalHaberLibroMayor;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JFormattedTextField jFormattedTextField1;
    public javax.swing.JFormattedTextField jFormattedTextField2;
    public javax.swing.JFormattedTextField jFormattedTextField3;
    public javax.swing.JFormattedTextField jFormattedTextField4;
    public javax.swing.JFormattedTextField jFormattedTextField5;
    public javax.swing.JFormattedTextField jFormattedTextField6;
    public javax.swing.JFormattedTextField jFormattedTextField7;
    public javax.swing.JFormattedTextField jFormattedTextField8;
    public javax.swing.JFormattedTextField jFormattedTextField9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JMenu menuAcciones;
    public javax.swing.JMenuItem menuItemCrearPeriodoContable;
    public javax.swing.JMenuItem munuItemCostoDeManoDeObra;
    public javax.swing.JMenuItem munuItemVerCatalogoDeCuenta;
    public javax.swing.JPanel panelAsientos;
    public javax.swing.JPanel panelGlobal;
    public javax.swing.JPanel panelMovimientos;
    public javax.swing.JPanel panelPeriodoContable;
    public javax.swing.JPanel panelTabBalanceGeneral;
    public javax.swing.JPanel panelTabEstadoDeResultado;
    public javax.swing.JTabbedPane panelTabGlobal;
    public javax.swing.JPanel panelTabLibroDiario;
    public javax.swing.JPanel panelTabLibroMayor;
    public javax.swing.JPanel panelTablaAsientos;
    public javax.swing.JPanel panelTablaMovimientos;
    public javax.swing.JPanel panelTitulo;
    public javax.swing.JPanel panelTotales;
    public javax.swing.JTable tbAsientosDeDiario;
    public javax.swing.JTable tbMovimientosCuentaEspecificaLibroMayor;
    public javax.swing.JTable tbMovimientosDeAsientosDeDiario;
    public javax.swing.JLabel txtAnioPeriodoContable;
    public javax.swing.JLabel txtCuentaLibroMayor;
    public javax.swing.JLabel txtMesPeriodoContable;
    public javax.swing.JLabel txtSaltoTotalCuentaLibroMayor;
    public javax.swing.JLabel txtTituloApp;
    public javax.swing.JLabel txtTotalDebeLibroMayor;
    public javax.swing.JLabel txtTotalHaberLibroMayor;
    // End of variables declaration//GEN-END:variables
}
