/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.github.joanhermay.sistema_sic.estadoderesultado;

/**
 *
 * @author joanhermay
 */
public class VistaEstadoDeResultado extends javax.swing.JDialog {

    /**
     * Creates new form VistaEstadoDeResultado
     */
    public VistaEstadoDeResultado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActivos = new javax.swing.JPanel();
        ftxtTotalActivos = new javax.swing.JFormattedTextField();
        txtTotalActivos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaActivos = new javax.swing.JTable();
        panelPasivos = new javax.swing.JPanel();
        ftxtTotalPasivos = new javax.swing.JFormattedTextField();
        txtTotalPasivos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelCapitalPatrimonio = new javax.swing.JPanel();
        ftxtTotalCapitalPatrimonio = new javax.swing.JFormattedTextField();
        txtTotalCapital = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCapitalPatrimonio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        panelActivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Activos"));

        txtTotalActivos.setText("TOTAL ACTIVOS");

        tablaActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(tablaActivos);

        javax.swing.GroupLayout panelActivosLayout = new javax.swing.GroupLayout(panelActivos);
        panelActivos.setLayout(panelActivosLayout);
        panelActivosLayout.setHorizontalGroup(
            panelActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(panelActivosLayout.createSequentialGroup()
                        .addComponent(txtTotalActivos)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtTotalActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelActivosLayout.setVerticalGroup(
            panelActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTotalActivos)
                    .addComponent(ftxtTotalActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPasivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Pasivos"));

        txtTotalPasivos.setText("TOTAL PASIVOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Monto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelPasivosLayout = new javax.swing.GroupLayout(panelPasivos);
        panelPasivos.setLayout(panelPasivosLayout);
        panelPasivosLayout.setHorizontalGroup(
            panelPasivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPasivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(panelPasivosLayout.createSequentialGroup()
                        .addComponent(txtTotalPasivos)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtTotalPasivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPasivosLayout.setVerticalGroup(
            panelPasivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelPasivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTotalPasivos)
                    .addComponent(ftxtTotalPasivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelCapitalPatrimonio.setBorder(javax.swing.BorderFactory.createTitledBorder("Capital"));

        txtTotalCapital.setText("TOTAL CAPITAL");

        tablaCapitalPatrimonio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Monto"
            }
        ));
        jScrollPane3.setViewportView(tablaCapitalPatrimonio);

        javax.swing.GroupLayout panelCapitalPatrimonioLayout = new javax.swing.GroupLayout(panelCapitalPatrimonio);
        panelCapitalPatrimonio.setLayout(panelCapitalPatrimonioLayout);
        panelCapitalPatrimonioLayout.setHorizontalGroup(
            panelCapitalPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapitalPatrimonioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCapitalPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
                    .addGroup(panelCapitalPatrimonioLayout.createSequentialGroup()
                        .addComponent(txtTotalCapital)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtTotalCapitalPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCapitalPatrimonioLayout.setVerticalGroup(
            panelCapitalPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapitalPatrimonioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelCapitalPatrimonioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCapital)
                    .addComponent(ftxtTotalCapitalPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panelPasivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelCapitalPatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPasivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelCapitalPatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftxtTotalActivos;
    public javax.swing.JFormattedTextField ftxtTotalCapitalPatrimonio;
    public javax.swing.JFormattedTextField ftxtTotalPasivos;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JPanel panelActivos;
    public javax.swing.JPanel panelCapitalPatrimonio;
    public javax.swing.JPanel panelPasivos;
    private javax.swing.JTable tablaActivos;
    public javax.swing.JTable tablaCapitalPatrimonio;
    private javax.swing.JLabel txtTotalActivos;
    public javax.swing.JLabel txtTotalCapital;
    public javax.swing.JLabel txtTotalPasivos;
    // End of variables declaration//GEN-END:variables
}
